linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - lll
    - maligned
    - gochecknoglobals
    - interfacer

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 50
